# This is the config file for building TileStache and running the test suite
# with Travis-ci.org

language: python

sudo: required
dist: trusty

python:
  - "2.7"

addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-9.4-postgis-2.2
      - python-dev
      - libgdal1-dev
      - python-werkzeug

virtualenv:
  system_site_packages: true

services:
  - memcached
  - postgresql

install:
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - pip install gdal==1.10
  - pip install nose coverage
  - pip install -r requirements.txt

before_script:
  - psql -U postgres -c "drop database if exists test_tilestache"
  - psql -U postgres -c "create database test_tilestache"
  - psql -U postgres -c "create extension postgis" -d test_tilestache

script:
  - nosetests -v --with-coverage --cover-package TileStache

notifications:
  email:
    recipients:
      - mike-travisci@teczno.com
